######################################################################
# Automatically generated by qmake (2.01a) ?? ???. 1 00:03:17 2012
######################################################################

QT      +=  core gui sql

TEMPLATE = app
TARGET = nameplates 


# Input
HEADERS += catalog.h element.h mainwindow.h
FORMS += mainwindow.ui
SOURCES += catalog.cpp main.cpp mainwindow.cpp
